import type { NewExerciseLibraryRow } from "../schema/exerciseLibrary";

type SeedExercise = Omit<NewExerciseLibraryRow, "id" | "createdAt" | "updatedAt">;

/**
 * Standard, well-established exercises — no invented movements. This is the
 * dataset agents/04-exercise-selector is constrained to (docs/AGENTS.md:
 * "never invents an exercise"). Not exhaustive; extend as real usage
 * surfaces gaps (e.g. more machine variants, more cardio modalities).
 */
export const EXERCISE_SEED: SeedExercise[] = [
  // ---- Chest ----
  {
    slug: "barbell-bench-press",
    name: "Supino reto com barra",
    description: "Movimento composto fundamental para peito, ombros e tríceps, feito deitado em um banco reto.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    level: "intermediate",
    instructions:
      "Deite no banco com os pés apoiados no chão. Segure a barra um pouco mais larga que os ombros, desça controladamente até o peito e empurre de volta até estender os braços.",
    commonMistakes: "Arquear excessivamente a lombar; deixar os cotovelos abrirem 90° em relação ao tronco; quicar a barra no peito.",
    contraindicationTags: [],
  },
  {
    slug: "dumbbell-bench-press",
    name: "Supino reto com halteres",
    description: "Variação do supino com halteres, permitindo maior amplitude e trabalho unilateral de estabilização.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Deitado no banco, segure um halter em cada mão na altura do peito e empurre para cima até estender os braços, controlando a descida.",
    commonMistakes: "Bater os halteres um no outro no topo; descer rápido demais sem controle.",
    contraindicationTags: [],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Supino inclinado com halteres",
    description: "Ênfase na porção superior do peitoral usando um banco inclinado.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    level: "intermediate",
    instructions: "Ajuste o banco entre 30-45°. Empurre os halteres para cima a partir da altura do peito superior, controlando a descida.",
    commonMistakes: "Inclinação excessiva do banco (vira exercício de ombro); amplitude incompleta.",
    contraindicationTags: [],
  },
  {
    slug: "push-up",
    name: "Flexão de braço",
    description: "Exercício de peso corporal para peito, ombros e tríceps, sem necessidade de equipamento.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps", "abs"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Mãos no chão na largura dos ombros, corpo reto da cabeça aos calcanhares. Desça o peito em direção ao chão e empurre de volta.",
    commonMistakes: "Deixar o quadril cair ou subir; amplitude incompleta.",
    contraindicationTags: [],
  },
  {
    slug: "cable-fly",
    name: "Crucifixo no cabo",
    description: "Exercício de isolamento para o peitoral usando polias cruzadas.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    level: "intermediate",
    instructions: "Em pé entre as torres, puxe as alças em um arco à frente do peito com cotovelos levemente flexionados, controlando o retorno.",
    commonMistakes: "Usar carga excessiva e transformar em movimento de pressão em vez de arco.",
    contraindicationTags: [],
  },
  {
    slug: "chest-press-machine",
    name: "Supino na máquina",
    description: "Variação guiada do supino, útil para iniciantes aprenderem o padrão de movimento com segurança.",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "machine",
    level: "beginner",
    instructions: "Ajuste o banco para que as alças fiquem na altura do peito. Empurre à frente até quase estender os braços e retorne controladamente.",
    commonMistakes: "Ajuste incorreto do assento, sobrecarregando os ombros.",
    contraindicationTags: [],
  },

  // ---- Back ----
  {
    slug: "deadlift",
    name: "Levantamento terra",
    description: "Um dos movimentos compostos mais completos, trabalhando posterior de coxa, glúteos, lombar e costas.",
    primaryMuscle: "back",
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: "barbell",
    level: "advanced",
    instructions: "Pés na largura do quadril, barra próxima às canelas. Mantenha a coluna neutra, quadril para trás, e levante estendendo quadril e joelhos ao mesmo tempo.",
    commonMistakes: "Arredondar a lombar; barra se afastando do corpo; hiperextensão no topo.",
    contraindicationTags: ["axial-spinal-loading", "breath-holding"],
  },
  {
    slug: "pull-up",
    name: "Barra fixa",
    description: "Exercício de peso corporal para as costas e bíceps, puxando o corpo até o queixo passar da barra.",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "forearms"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Pendurado na barra com pegada pronada, puxe o corpo para cima até o queixo ultrapassar a barra e desça controladamente.",
    commonMistakes: "Usar embalo excessivo (kipping) sem essa intenção; amplitude incompleta.",
    contraindicationTags: [],
  },
  {
    slug: "lat-pulldown",
    name: "Puxada alta (pulley)",
    description: "Variação guiada da barra fixa, permitindo ajuste de carga.",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "forearms"],
    equipment: "cable",
    level: "beginner",
    instructions: "Sentado, segure a barra mais larga que os ombros e puxe em direção à parte superior do peito, controlando o retorno.",
    commonMistakes: "Puxar atrás da nuca; usar impulso do tronco.",
    contraindicationTags: [],
  },
  {
    slug: "barbell-bent-over-row",
    name: "Remada curvada com barra",
    description: "Movimento composto para espessura das costas, feito com o tronco inclinado à frente.",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "barbell",
    level: "intermediate",
    instructions: "Incline o tronco para frente mantendo a coluna neutra, puxe a barra em direção ao abdômen e desça controladamente.",
    commonMistakes: "Arredondar a lombar; usar impulso do corpo em vez dos músculos das costas.",
    contraindicationTags: ["axial-spinal-loading"],
  },
  {
    slug: "seated-cable-row",
    name: "Remada sentada no cabo",
    description: "Exercício de puxada horizontal com apoio, bom para aprender a ativar as costas sem exigir estabilização lombar intensa.",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    level: "beginner",
    instructions: "Sentado com joelhos levemente flexionados, puxe a alça em direção ao abdômen mantendo o tronco ereto.",
    commonMistakes: "Balançar o tronco para gerar impulso; encolher os ombros durante a puxada.",
    contraindicationTags: [],
  },
  {
    slug: "dumbbell-single-arm-row",
    name: "Remada unilateral com halter",
    description: "Trabalha as costas unilateralmente, com um joelho e uma mão apoiados no banco.",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Apoie um joelho e uma mão no banco, puxe o halter em direção ao quadril mantendo a coluna neutra.",
    commonMistakes: "Rotacionar o tronco durante a puxada.",
    contraindicationTags: [],
  },
  {
    slug: "superman",
    name: "Superman",
    description: "Exercício de peso corporal para a musculatura lombar e extensores da coluna.",
    primaryMuscle: "back",
    secondaryMuscles: ["glutes"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Deitado de bruços, eleve simultaneamente braços e pernas do chão, contraindo a lombar, e retorne controladamente.",
    commonMistakes: "Movimento muito rápido, usando embalo.",
    contraindicationTags: [],
  },

  // ---- Shoulders ----
  {
    slug: "overhead-press",
    name: "Desenvolvimento militar com barra",
    description: "Movimento composto em pé para ombros, pressionando a barra acima da cabeça.",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    level: "advanced",
    instructions: "Em pé, barra na altura dos ombros, pressione para cima até estender os braços, mantendo o core contraído.",
    commonMistakes: "Hiperestender a lombar para compensar mobilidade de ombro limitada.",
    contraindicationTags: ["axial-spinal-loading", "breath-holding"],
  },
  {
    slug: "dumbbell-shoulder-press",
    name: "Desenvolvimento com halteres",
    description: "Variação do desenvolvimento feita sentado ou em pé, com halteres.",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    level: "intermediate",
    instructions: "Sentado com apoio nas costas, pressione os halteres acima da cabeça até quase estender os braços.",
    commonMistakes: "Arquear a lombar no banco sem apoio adequado.",
    contraindicationTags: [],
  },
  {
    slug: "lateral-raise",
    name: "Elevação lateral",
    description: "Isolamento para a porção lateral do deltoide.",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Em pé, eleve os halteres lateralmente até a altura dos ombros, com leve flexão nos cotovelos, e desça controladamente.",
    commonMistakes: "Usar impulso do tronco; elevar acima da linha dos ombros.",
    contraindicationTags: [],
  },
  {
    slug: "face-pull",
    name: "Face pull no cabo",
    description: "Exercício para deltoide posterior e rotadores externos, importante para saúde do ombro.",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "cable",
    level: "beginner",
    instructions: "Com a polia na altura do rosto, puxe a corda em direção à testa, separando as mãos e rotacionando os ombros para fora.",
    commonMistakes: "Usar carga alta demais, perdendo a forma.",
    contraindicationTags: [],
  },
  {
    slug: "arnold-press",
    name: "Desenvolvimento Arnold",
    description: "Variação do desenvolvimento com rotação, trabalhando os três feixes do deltoide.",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    level: "intermediate",
    instructions: "Comece com os halteres à frente do rosto, palmas voltadas para você, e pressione para cima enquanto rotaciona as palmas para frente.",
    commonMistakes: "Rotação incompleta; carga excessiva prejudicando a técnica.",
    contraindicationTags: [],
  },

  // ---- Biceps ----
  {
    slug: "barbell-curl",
    name: "Rosca direta com barra",
    description: "Exercício clássico de isolamento para o bíceps.",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    level: "beginner",
    instructions: "Em pé, segure a barra com pegada supinada e flexione os cotovelos, elevando a barra até a altura dos ombros.",
    commonMistakes: "Usar embalo do quadril; mover os cotovelos para frente.",
    contraindicationTags: [],
  },
  {
    slug: "dumbbell-hammer-curl",
    name: "Rosca martelo",
    description: "Variação da rosca com pegada neutra, enfatizando também o braquial e antebraço.",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Segure os halteres com pegada neutra (palmas viradas uma para a outra) e flexione os cotovelos alternada ou simultaneamente.",
    commonMistakes: "Balançar o tronco para gerar impulso.",
    contraindicationTags: [],
  },
  {
    slug: "cable-curl",
    name: "Rosca no cabo",
    description: "Rosca de bíceps usando o cabo, mantendo tensão constante no músculo.",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "cable",
    level: "intermediate",
    instructions: "Em pé de frente para a polia baixa, flexione os cotovelos puxando a barra em direção aos ombros.",
    commonMistakes: "Afastar os cotovelos do tronco durante o movimento.",
    contraindicationTags: [],
  },

  // ---- Triceps ----
  {
    slug: "triceps-pushdown",
    name: "Tríceps na polia (pushdown)",
    description: "Exercício de isolamento para o tríceps usando a polia alta.",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    level: "beginner",
    instructions: "De frente para a polia alta, mantenha os cotovelos fixos ao lado do corpo e estenda os braços empurrando a barra para baixo.",
    commonMistakes: "Afastar os cotovelos do corpo; usar o peso do corpo para empurrar.",
    contraindicationTags: [],
  },
  {
    slug: "skull-crusher",
    name: "Tríceps testa (skull crusher)",
    description: "Exercício de isolamento para tríceps feito deitado, com barra ou halteres.",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: "barbell",
    level: "intermediate",
    instructions: "Deitado no banco, segure a barra acima do peito e flexione apenas os cotovelos, descendo a barra em direção à testa.",
    commonMistakes: "Mover os ombros durante o exercício; descer rápido demais.",
    contraindicationTags: [],
  },
  {
    slug: "close-grip-bench-press",
    name: "Supino fechado",
    description: "Variação do supino com pegada estreita, priorizando o tríceps.",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "barbell",
    level: "intermediate",
    instructions: "Deitado no banco, segure a barra com as mãos na largura dos ombros ou um pouco menos, e desça controladamente até o peito.",
    commonMistakes: "Pegada muito fechada, sobrecarregando os punhos.",
    contraindicationTags: [],
  },
  {
    slug: "dips",
    name: "Paralelas (mergulho)",
    description: "Exercício de peso corporal para tríceps e peito, feito em barras paralelas.",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Apoiado nas paralelas com braços estendidos, desça flexionando os cotovelos até 90° e empurre de volta.",
    commonMistakes: "Descer demais, sobrecarregando o ombro.",
    contraindicationTags: ["high-joint-impact"],
  },

  // ---- Quadriceps ----
  {
    slug: "barbell-back-squat",
    name: "Agachamento livre com barra",
    description: "Movimento composto fundamental para pernas, com a barra apoiada nas costas.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "barbell",
    level: "advanced",
    instructions: "Barra apoiada no trapézio, pés na largura dos ombros. Agache até pelo menos 90° de flexão de joelho, mantendo o peito erguido, e suba.",
    commonMistakes: "Joelhos colapsando para dentro; perder a curvatura neutra da lombar; não atingir profundidade adequada.",
    contraindicationTags: ["axial-spinal-loading", "breath-holding", "high-joint-stress"],
  },
  {
    slug: "goblet-squat",
    name: "Agachamento goblet",
    description: "Variação de agachamento segurando um halter ou kettlebell junto ao peito, ótima para aprender o padrão de movimento.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Segure o halter verticalmente junto ao peito e agache mantendo o tronco ereto e os cotovelos entre os joelhos na parte baixa.",
    commonMistakes: "Inclinar o tronco excessivamente para frente.",
    contraindicationTags: [],
  },
  {
    slug: "leg-press",
    name: "Leg press",
    description: "Exercício guiado de pernas em máquina, permitindo cargas altas com menor exigência de estabilização.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    level: "beginner",
    instructions: "Sentado na máquina, pés na plataforma na largura dos ombros, flexione os joelhos até 90° e empurre de volta sem travar os joelhos.",
    commonMistakes: "Descer demais, arredondando a lombar contra o encosto.",
    contraindicationTags: [],
  },
  {
    slug: "walking-lunge",
    name: "Afundo caminhando",
    description: "Exercício unilateral de pernas, feito dando passos alternados à frente.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    level: "intermediate",
    instructions: "Dê um passo à frente e desça até o joelho de trás quase tocar o chão, depois empurre para o próximo passo.",
    commonMistakes: "Passo curto demais, sobrecarregando o joelho da frente.",
    contraindicationTags: [],
  },
  {
    slug: "bodyweight-squat",
    name: "Agachamento livre (peso corporal)",
    description: "Versão sem carga do agachamento, ideal para iniciantes absolutos.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Pés na largura dos ombros, agache mantendo o peito erguido e o peso nos calcanhares, até onde a mobilidade permitir com boa forma.",
    commonMistakes: "Levantar os calcanhares do chão.",
    contraindicationTags: [],
  },
  {
    slug: "leg-extension",
    name: "Cadeira extensora",
    description: "Exercício de isolamento para o quadríceps em máquina.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    instructions: "Sentado na máquina, estenda os joelhos até quase travar, contraindo o quadríceps, e desça controladamente.",
    commonMistakes: "Usar impulso; estender com força excessiva travando o joelho.",
    contraindicationTags: [],
  },
  {
    slug: "jump-squat",
    name: "Agachamento com salto",
    description: "Variação pliométrica do agachamento, adicionando um salto explosivo.",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "calves"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Agache e exploda para cima em um salto, aterrissando suavemente de volta na posição de agachamento.",
    commonMistakes: "Aterrissagem rígida, sem amortecer com os joelhos.",
    contraindicationTags: ["high-joint-impact", "high-cardiovascular-intensity"],
  },

  // ---- Hamstrings ----
  {
    slug: "romanian-deadlift",
    name: "Levantamento terra romeno",
    description: "Variação do terra com foco em posterior de coxa, com menor flexão de joelho.",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    level: "intermediate",
    instructions: "Segure a barra à frente das coxas, empurre o quadril para trás mantendo os joelhos levemente flexionados, descendo até sentir alongamento no posterior de coxa.",
    commonMistakes: "Arredondar a lombar; flexionar demais os joelhos, virando um agachamento.",
    contraindicationTags: ["axial-spinal-loading"],
  },
  {
    slug: "lying-leg-curl",
    name: "Mesa flexora",
    description: "Exercício de isolamento para os isquiotibiais em máquina.",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    instructions: "Deitado de bruços na máquina, flexione os joelhos trazendo o calcanhar em direção ao glúteo, e retorne controladamente.",
    commonMistakes: "Elevar o quadril do banco durante o movimento.",
    contraindicationTags: [],
  },
  {
    slug: "glute-ham-raise",
    name: "Glute-ham raise",
    description: "Exercício avançado para posterior de coxa e glúteos usando um banco específico ou apoio para os pés.",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Com os pés fixos, desça o tronco controladamente à frente e retorne usando a força dos isquiotibiais.",
    commonMistakes: "Descer rápido demais sem controle excêntrico.",
    contraindicationTags: [],
  },

  // ---- Glutes ----
  {
    slug: "hip-thrust",
    name: "Elevação de quadril (hip thrust)",
    description: "Um dos exercícios mais eficazes para ativação e força de glúteos.",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "barbell",
    level: "intermediate",
    instructions: "Costas apoiadas em um banco, barra sobre o quadril, eleve o quadril até o corpo formar uma linha reta dos ombros aos joelhos.",
    commonMistakes: "Hiperestender a lombar no topo em vez de usar os glúteos.",
    contraindicationTags: [],
  },
  {
    slug: "glute-bridge",
    name: "Ponte de glúteo",
    description: "Versão de peso corporal do hip thrust, feita com as costas no chão.",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Deitado com joelhos flexionados e pés no chão, eleve o quadril contraindo os glúteos, e desça controladamente.",
    commonMistakes: "Empurrar com a lombar em vez dos glúteos.",
    contraindicationTags: [],
  },
  {
    slug: "cable-kickback",
    name: "Coice no cabo",
    description: "Exercício de isolamento para glúteos usando a polia baixa.",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "cable",
    level: "beginner",
    instructions: "Com o tornozelo preso à polia baixa, estenda a perna para trás contraindo o glúteo, e retorne controladamente.",
    commonMistakes: "Usar o tronco para gerar impulso em vez do glúteo.",
    contraindicationTags: [],
  },

  // ---- Calves ----
  {
    slug: "standing-calf-raise",
    name: "Elevação de panturrilha em pé",
    description: "Exercício de isolamento para as panturrilhas, feito em pé.",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    instructions: "Em pé na máquina, eleve os calcanhares o máximo possível e desça controladamente até alongar a panturrilha.",
    commonMistakes: "Amplitude curta demais; usar embalo.",
    contraindicationTags: [],
  },
  {
    slug: "seated-calf-raise",
    name: "Elevação de panturrilha sentado",
    description: "Variação sentada que enfatiza o sóleo.",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    instructions: "Sentado com os joelhos sob o apoio, eleve os calcanhares e desça controladamente com amplitude completa.",
    commonMistakes: "Movimento rápido demais, sem pausa no topo.",
    contraindicationTags: [],
  },

  // ---- Abs ----
  {
    slug: "plank",
    name: "Prancha abdominal",
    description: "Exercício isométrico para o core inteiro, sustentando o corpo em linha reta.",
    primaryMuscle: "abs",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Apoiado nos antebraços e pontas dos pés, mantenha o corpo reto da cabeça aos calcanhares, contraindo o abdômen.",
    commonMistakes: "Deixar o quadril subir ou cair.",
    contraindicationTags: [],
  },
  {
    slug: "cable-crunch",
    name: "Abdominal na polia (cable crunch)",
    description: "Exercício de abdômen com resistência progressiva usando a polia alta.",
    primaryMuscle: "abs",
    secondaryMuscles: [],
    equipment: "cable",
    level: "intermediate",
    instructions: "Ajoelhado de frente para a polia alta, flexione o tronco em direção aos joelhos contraindo o abdômen.",
    commonMistakes: "Puxar com os braços em vez de flexionar com o abdômen.",
    contraindicationTags: [],
  },
  {
    slug: "hanging-leg-raise",
    name: "Elevação de pernas na barra",
    description: "Exercício avançado de abdômen inferior, feito pendurado em uma barra.",
    primaryMuscle: "abs",
    secondaryMuscles: ["forearms"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Pendurado na barra, eleve as pernas estendidas ou flexionadas até a altura do quadril, controlando o retorno.",
    commonMistakes: "Usar embalo do corpo em vez de força abdominal.",
    contraindicationTags: [],
  },
  {
    slug: "russian-twist",
    name: "Rotação russa",
    description: "Exercício rotacional para os oblíquos.",
    primaryMuscle: "abs",
    secondaryMuscles: [],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Sentado com o tronco levemente inclinado para trás, rotacione o tronco de um lado para o outro.",
    commonMistakes: "Mover apenas os braços em vez de rotacionar o tronco.",
    contraindicationTags: [],
  },

  // ---- Forearms ----
  {
    slug: "wrist-curl",
    name: "Rosca de punho",
    description: "Exercício de isolamento para os flexores do antebraço.",
    primaryMuscle: "forearms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    instructions: "Antebraços apoiados nas coxas ou em um banco, flexione os punhos elevando o peso, e desça controladamente.",
    commonMistakes: "Usar carga alta demais, limitando a amplitude.",
    contraindicationTags: [],
  },
  {
    slug: "farmers-carry",
    name: "Farmer's carry (caminhada com peso)",
    description: "Exercício funcional para força de pegada, antebraços e estabilização do core, caminhando com halteres pesados.",
    primaryMuscle: "forearms",
    secondaryMuscles: ["abs", "full_body"],
    equipment: "dumbbell",
    level: "intermediate",
    instructions: "Segure um halter pesado em cada mão e caminhe mantendo a postura ereta e o core contraído.",
    commonMistakes: "Deixar os ombros caírem para frente.",
    contraindicationTags: [],
  },

  // ---- Full body ----
  {
    slug: "burpee",
    name: "Burpee",
    description: "Exercício de corpo inteiro de alta intensidade, combinando agachamento, prancha e salto.",
    primaryMuscle: "full_body",
    secondaryMuscles: ["chest", "quadriceps", "cardio"],
    equipment: "bodyweight",
    level: "advanced",
    instructions: "Agache, apoie as mãos no chão, jogue os pés para trás em posição de prancha, retorne e salte para cima.",
    commonMistakes: "Perder a forma da prancha; aterrissar rigidamente do salto.",
    contraindicationTags: ["high-cardiovascular-intensity", "high-joint-impact"],
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell swing",
    description: "Movimento balístico de quadril trabalhando posterior de coxa, glúteos e core.",
    primaryMuscle: "full_body",
    secondaryMuscles: ["glutes", "hamstrings", "back"],
    equipment: "kettlebell",
    level: "intermediate",
    instructions: "Com o kettlebell entre as pernas, projete o quadril à frente para balançar o peso até a altura dos ombros, usando o quadril, não os braços.",
    commonMistakes: "Agachar em vez de dobrar o quadril; usar os braços para levantar o peso.",
    contraindicationTags: ["high-cardiovascular-intensity"],
  },
  {
    slug: "dumbbell-thruster",
    name: "Thruster com halteres",
    description: "Combinação de agachamento com desenvolvimento, trabalhando pernas e ombros em um movimento só.",
    primaryMuscle: "full_body",
    secondaryMuscles: ["quadriceps", "shoulders"],
    equipment: "dumbbell",
    level: "advanced",
    instructions: "Segure os halteres na altura dos ombros, agache, e ao subir use o impulso para pressionar os halteres acima da cabeça.",
    commonMistakes: "Separar os dois movimentos em vez de fazer um fluido.",
    contraindicationTags: ["high-cardiovascular-intensity"],
  },

  // ---- Cardio / conditioning ----
  {
    slug: "jogging",
    name: "Corrida leve (trote)",
    description: "Atividade cardiovascular de intensidade moderada.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps", "calves"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Corra em ritmo confortável, respiração controlada, mantendo postura ereta.",
    commonMistakes: "Passadas muito longas; postura curvada para frente.",
    contraindicationTags: ["high-cardiovascular-intensity", "high-joint-impact"],
  },
  {
    slug: "stationary-bike",
    name: "Bicicleta ergométrica",
    description: "Cardio de baixo impacto nas articulações, bom para todos os níveis.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps"],
    equipment: "machine",
    level: "beginner",
    instructions: "Ajuste o banco à altura do quadril, pedale em ritmo constante ajustando a resistência conforme o objetivo.",
    commonMistakes: "Selim muito baixo, sobrecarregando o joelho.",
    contraindicationTags: ["high-cardiovascular-intensity"],
  },
  {
    slug: "rowing-machine",
    name: "Remo ergométrico",
    description: "Cardio de corpo inteiro de baixo impacto, combinando pernas, costas e braços.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["back", "hamstrings"],
    equipment: "machine",
    level: "intermediate",
    instructions: "Empurre com as pernas primeiro, depois puxe a alça em direção ao abdômen, e retorne na ordem inversa.",
    commonMistakes: "Puxar com os braços antes de estender as pernas.",
    contraindicationTags: ["high-cardiovascular-intensity"],
  },
  {
    slug: "jump-rope",
    name: "Pular corda",
    description: "Cardio de alta intensidade e baixo custo de equipamento.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["calves"],
    equipment: "bodyweight",
    level: "intermediate",
    instructions: "Gire a corda com os punhos, saltando o suficiente para a corda passar sob os pés, aterrissando suavemente.",
    commonMistakes: "Saltos muito altos, desperdiçando energia.",
    contraindicationTags: ["high-cardiovascular-intensity", "high-joint-impact"],
  },
  {
    slug: "mountain-climber",
    name: "Mountain climber",
    description: "Exercício dinâmico de corpo inteiro combinando cardio e ativação do core.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["abs", "shoulders"],
    equipment: "bodyweight",
    level: "intermediate",
    instructions: "Em posição de prancha, alterne trazendo os joelhos em direção ao peito rapidamente, mantendo o quadril estável.",
    commonMistakes: "Deixar o quadril subir; perder a estabilidade do core.",
    contraindicationTags: ["high-cardiovascular-intensity"],
  },
  {
    slug: "brisk-walking",
    name: "Caminhada rápida",
    description: "Atividade cardiovascular de baixo impacto e baixa intensidade, ótima para iniciantes ou condições cardiovasculares que exigem cautela.",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps", "calves"],
    equipment: "bodyweight",
    level: "beginner",
    instructions: "Caminhe em ritmo acelerado, mantendo a postura ereta e uma respiração confortável durante toda a atividade.",
    commonMistakes: "Ritmo inconsistente; postura curvada.",
    contraindicationTags: [],
  },
];
